Project:
  Name: E-Commerce Platform
  Description: A platform to sell products
  C_Backend:
    Name: Backend Operations
    Description: Handles the backend functionalities like product management in the
      database
    P_AddProduct:
      Name: Add Product to Database
      Description: Adds a product to the platform's database
      Input:
        Name: productDetails
        Type: Object
        Description: Object containing the details of the product to be added
        Properties:
          Name:
            Type: String
            Description: Name of the product
          Price:
            Type: Number
            Description: Price of the product
          Description:
            Type: String
            Description: Description of the product
        Value: '{"key": "6L3O9"}'
      Output:
        Name: productResponse
        Type: Object
        Description: Object containing the response with product ID and details
        Properties:
          ProductId:
            Type: String
            Description: Id of the product
          Name:
            Type: String
            Description: Name of the product
          Price:
            Type: Number
            Description: Price of the product
          Description:
            Type: String
            Description: Description of the product
        Value: '{"key": "6IDIU"}'
    P_GetProduct:
      Name: Retrieve Product from Database
      Description: Fetches a product's details from the platform's database
      Input:
        Name: productId
        Type: Object
        Description: Object containing the ID of the product to be fetched
        Properties:
          ProductId:
            Type: String
            Description: Id of the product
        Value: '{"key": "6EWRY"}'
      Output:
        Name: productDetails
        Type: Object
        Description: Object containing the details of the requested product
        Properties:
          ProductId:
            Type: String
            Description: Id of the product
          Name:
            Type: String
            Description: Name of the product
          Price:
            Type: Number
            Description: Price of the product
          Description:
            Type: String
            Description: Description of the product
        Value: '{"key": "KFZVH"}'
    GLUE:
      Graph: P_AddProduct -> P_GetProduct
      Description: Connects the add and get product processes for backend integration
  C_Frontend:
    Name: Frontend Interface
    Description: Manages the frontend interactions and UI components for product display
      and management
    P_AddProduct:
      Name: Frontend Add Product
      Description: Interface to add product to the platform via backend
      Input:
        Type: Object
        Description: Object containing the details of the product to be added
        Properties:
          Name:
            Type: String
            Description: Name of the product
          Price:
            Type: Number
            Description: Price of the product
          Description:
            Type: String
            Description: Description of the product
        Name: productDetails
        Value: '{"key": "BMJMY"}'
      Output:
        Type: Object
        Description: Object containing the response with product ID and details
        Properties:
          ProductId:
            Type: String
            Description: Id of the product
          Name:
            Type: String
            Description: Name of the product
          Price:
            Type: Number
            Description: Price of the product
          Description:
            Type: String
            Description: Description of the product
        Name: productResponse
        Value: '{"key": "D53BE"}'
    P_GetProduct:
      Name: Frontend Get Product
      Description: Interface to retrieve product details from the platform
      Input:
        Type: Object
        Description: Object containing the ID of the product to be fetched
        Properties:
          ProductId:
            Type: String
            Description: Id of the product
        Name: productIdObject
        Value: '{"key": "BM1AB"}'
      Output:
        Type: Object
        Description: Object containing the details of the requested product
        Properties:
          ProductId:
            Type: String
            Description: Id of the product
          Name:
            Type: String
            Description: Name of the product
          Price:
            Type: Number
            Description: Price of the product
          Description:
            Type: String
            Description: Description of the product
        Name: requestObjectResponse
        Value: '{"key": "BUM8K"}'
    GLUE:
      Graph: P_AddProduct -> P_GetProduct
      Description: Connects the add and get product processes for frontend integration
