Project:
  Name: Pomodoro Timer CLI
  Description: A command line-based Pomodoro Timer with features to start, pause,
    resume, stop, display time remaining, and reset the timer.
  C_TimerManagement:
    Name: Timer Management
    Description: Manages the core functionalities of the Pomodoro Timer.
    P_StartTimer:
      Name: Start Timer
      Description: Starts the timer for a specified duration.
      Input:
        Name: duration
        Type: Number
        Description: Duration for the timer in minutes (25/15/5).
        Value: 25
      Output:
        Name: timerStatus
        Type: String
        Description: Status message indicating the timer has started.
        Value: Timer started for 25 minutes.
    P_PauseTimer:
      Name: Pause Timer
      Description: Pauses the ongoing timer.
      Input: {}
      Output:
        Name: timerStatus
        Type: String
        Description: Status message indicating the timer has been paused.
        Value: Timer paused.
    P_ResumeTimer:
      Name: Resume Timer
      Description: Resumes the paused timer.
      Input: {}
      Output:
        Name: timerStatus
        Type: String
        Description: Status message indicating the timer has resumed.
        Value: Timer resumed.
    P_StopTimer:
      Name: Stop Timer
      Description: Stops the ongoing timer.
      Input: {}
      Output:
        Name: timerStatus
        Type: String
        Description: Status message indicating the timer has stopped.
        Value: Timer stopped.
    P_DisplayTimeRemaining:
      Name: Display Time Remaining
      Description: Displays the time remaining on the ongoing timer.
      Input: {}
      Output:
        Name: timeRemaining
        Type: String
        Description: Displays the time remaining in minutes and seconds.
        Value: 'Time remaining: 24:30.'
    P_ResetTimer:
      Name: Reset Timer
      Description: Resets the timer to its initial state.
      Input: {}
      Output:
        Name: timerStatus
        Type: String
        Description: Status message indicating the timer has been reset.
        Value: Timer reset.
    GLUE:
      Graph: 'P_StartTimer -> P_PauseTimer -> P_ResumeTimer -> P_StopTimer, P_DisplayTimeRemaining,
        P_ResetTimer

        '
      Description: Connects all the parts to handle the timer's lifecycle and functionalities.
  C_CLI:
    Name: Command Line Interface
    Description: Handles user interaction with the Pomodoro Timer through the command
      line.
    P_CLI_Loop:
      Name: CLI Loop
      Description: Main loop to process user commands and interact with the Timer
        Management component.
      Input:
        Name: userCommand
        Type: String
        Description: The command entered by the user (start, pause, resume, stop,
          display, reset).
        Value: start 25
      Output:
        Name: outputMessage
        Type: String
        Description: The output message to display to the user based on the action
          performed.
        Value: Timer started for 25 minutes.
    GLUE:
      Graph: P_CLI_Loop
      Description: Connects the command line interface loop with the timer management
        functionalities.
